---
# tasks file for jpnewman.elk-logstash-shipper

- name: Get Logstash plugins
  shell: bin/logstash-plugin list chdir=/usr/share/logstash
  register: logstash_installed_plugins
  changed_when: false

- name: Installing Logstash Plugins
  shell: bin/logstash-plugin install {{ item }} chdir=/usr/share/logstash
  notify: restart logstash
  when: item not in logstash_installed_plugins.stdout_lines
  with_items: "{{ logstash_plugins }}"
